### ISSUE TITLE
Warning in Console about gettin Texture of Player

### ISSUE THREAD

**Issue by CptGummiball** [granny/Pl3xMap-test#18]
Everything works fine even with this warning, but its spamming the console.

[01:52:53 WARN]: javax.imageio.IIOException: Can't get input stream from URL!
[01:52:53 WARN]:        at java.desktop/javax.imageio.ImageIO.read(ImageIO.java:1407)
[01:52:53 WARN]:        at Pl3xMap-1.20.4-477.jar//net.pl3x.map.core.player.PlayerTexture.run(PlayerTexture.java:76)
[01:52:53 WARN]: Caused by: java.net.ConnectException: Connection timed out: connect
[01:52:53 WARN]:        at java.base/sun.nio.ch.Net.connect0(Native Method)
[01:52:53 WARN]:        at java.base/sun.nio.ch.Net.connect(Net.java:589)
[01:52:53 WARN]:        at java.base/sun.nio.ch.Net.connect(Net.java:578)
[01:52:53 WARN]:        at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:583)
[01:52:53 WARN]:        at java.base/java.net.Socket.connect(Socket.java:751)
[01:52:53 WARN]:        at java.base/java.net.Socket.connect(Socket.java:686)
[01:52:53 WARN]:        at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:183)
[01:52:53 WARN]:        at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:531)
[01:52:53 WARN]:        at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:636)
[01:52:53 WARN]:        at java.base/sun.net.www.http.HttpClient.<init>(HttpClient.java:280)
[01:52:53 WARN]:        at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:386)
[01:52:53 WARN]:        at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:408)
[01:52:53 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1304)
[01:52:53 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1237)
[01:52:53 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1123)
[01:52:53 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:1052)
[01:52:53 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1675)
[01:52:53 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1599)
[01:52:53 WARN]:        at java.base/java.net.URL.openStream(URL.java:1325)
[01:52:53 WARN]:        at java.desktop/javax.imageio.ImageIO.read(ImageIO.java:1405)
[01:52:53 WARN]:        ... 1 more

**Comment by granny** [comment]
@CptGummiball Could you share your whole log using https://mclo.gs/?

**Comment by CptGummiball** [comment]
Yes! Here it is https://mclo.gs/h5Mpgk5

Please note that we were still in the server update phase. All other bugs have already been fixed. The message from Pl3xmap only occurs very rarely. But we have already observed these in the past. 
As I mentioned before, the map still works perfectly.

**Comment by granny** [comment]
I've gone ahead and made the warning stop printing the stacktrace to lower spam. That warning appears because Pl3xMap fails to open the texture url attached to a player, which makes this is a network issue. `Caused by: java.net.ConnectException: Connection timed out: connect`. Not sure why it happens rarely.
