### ISSUE TITLE
Support LZ4 Compression Type

### ISSUE THREAD

**Issue by sternschnaube** [granny/Pl3xMap-test#44]
Changed region-file-compression to lz4 and was running the world optimize option. After that it appeared.

[Pl3xMap] [ERROR] Failed to scan world minecraft:overworld at region Point[x=11, z=5]
[08:39:31] [Pl3xMap-Renderer-0/INFO]: [STDERR]: java.lang.RuntimeException: java.io.IOException: Invalid compression type 4
[08:39:31] [Pl3xMap-Renderer-0/INFO]: [STDERR]: 	at net.pl3x.map.core.renderer.task.RegionScanTask.loadRegion(RegionScanTask.java:111)
[08:39:31] [Pl3xMap-Renderer-0/INFO]: [STDERR]: 	at net.pl3x.map.core.renderer.task.RegionScanTask.run(RegionScanTask.java:89)
[08:39:31] [Pl3xMap-Renderer-0/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
[08:39:31] [Pl3xMap-Renderer-0/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796)
[08:39:31] [Pl3xMap-Renderer-0/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
[08:39:31] [Pl3xMap-Renderer-0/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
[08:39:31] [Pl3xMap-Renderer-0/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
[08:39:31] [Pl3xMap-Renderer-0/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
[08:39:31] [Pl3xMap-Renderer-0/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
[08:39:31] [Pl3xMap-Renderer-0/INFO]: [STDERR]: Caused by: java.io.IOException: Invalid compression type 4
[08:39:31] [Pl3xMap-Renderer-0/INFO]: [STDERR]: 	at net.pl3x.map.core.world.Region.loadChunk(Region.java:128)
[08:39:31] [Pl3xMap-Renderer-0/INFO]: [STDERR]: 	at net.pl3x.map.core.world.Region.loadChunks(Region.java:109)
[08:39:31] [Pl3xMap-Renderer-0/INFO]: [STDERR]: 	at net.pl3x.map.core.renderer.task.RegionScanTask.loadRegion(RegionScanTask.java:109)
[08:39:31] [Pl3xMap-Renderer-0/INFO]: [STDERR]: 	... 8 more

**Comment by granny** [comment]
lz4 is currently unsupported. Will look into implementing support for it sometime this week.

**Comment by sternschnaube** [comment]
Good to know, thanks 😄

**Comment by granny** [comment]
Should work fine now :) Let me know if you run into any issues!
