### ISSUE TITLE
Support uncompressed world files

### ISSUE THREAD

**Issue by ssterling** [granny/Pl3xMap-test#45]
Because I wanted to take advantage of [ZFS](https://docs.freebsd.org/en/books/handbook/zfs/)’ filesystem-level compression, I set `compression-format: NONE` in my [paper-global.yml](https://docs.papermc.io/paper/reference/global-configuration).  Now, having decided to try out Pl3xMap, I’m getting an error that it’s unsupported.

Sample error message is as follows:

```
[19:44:37] [Pl3xMap-Renderer-7/INFO]: [Pl3xMap] [ERROR] Failed to scan world world at region Point[x=1, z=-5]
[19:44:37] [Pl3xMap-Renderer-7/WARN]: java.lang.RuntimeException: java.io.IOException: Invalid compression type 3
[19:44:37] [Pl3xMap-Renderer-7/WARN]: 	at Pl3xMap-1.20.6-496.jar//net.pl3x.map.core.renderer.task.RegionScanTask.loadRegion(RegionScanTask.java:111)
[19:44:37] [Pl3xMap-Renderer-7/WARN]: 	at Pl3xMap-1.20.6-496.jar//net.pl3x.map.core.renderer.task.RegionScanTask.run(RegionScanTask.java:89)
[19:44:37] [Pl3xMap-Renderer-7/WARN]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
[19:44:37] [Pl3xMap-Renderer-7/WARN]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796)
[19:44:37] [Pl3xMap-Renderer-7/WARN]: 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
[19:44:37] [Pl3xMap-Renderer-7/WARN]: 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
[19:44:37] [Pl3xMap-Renderer-7/WARN]: 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
[19:44:37] [Pl3xMap-Renderer-7/WARN]: 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
[19:44:37] [Pl3xMap-Renderer-7/WARN]: 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
[19:44:37] [Pl3xMap-Renderer-7/WARN]: Caused by: java.io.IOException: Invalid compression type 3
[19:44:37] [Pl3xMap-Renderer-7/WARN]: 	at Pl3xMap-1.20.6-496.jar//net.pl3x.map.core.world.Region.loadChunk(Region.java:130)
[19:44:37] [Pl3xMap-Renderer-7/WARN]: 	at Pl3xMap-1.20.6-496.jar//net.pl3x.map.core.world.Region.loadChunks(Region.java:111)
[19:44:37] [Pl3xMap-Renderer-7/WARN]: 	at Pl3xMap-1.20.6-496.jar//net.pl3x.map.core.renderer.task.RegionScanTask.loadRegion(RegionScanTask.java:109)
[19:44:37] [Pl3xMap-Renderer-7/WARN]: 	... 8 more
```

**Comment by ssterling** [comment]
Beat me to it!  Wasn’t expecting that.
