### ISSUE TITLE
Plugin not starting. Issue with internal webserver.

### ISSUE THREAD

**Issue by mitch0s** [granny/Pl3xMap-test#59]
When I start the server, or use `/reload confirm` this is the error that occurs in terminal.
```
[06:56:48] [Server thread/ERROR]: Error occurred while enabling Pl3xMap v1.20.4-492 (Is it up to date?)
java.lang.NoSuchMethodError: 'net.minecraft.core.RegistryAccess$Frozen net.minecraft.server.MinecraftServer.aZ()'
	at Pl3xMap-1.20.4-492.jar/net.pl3x.map.bukkit.Pl3xMapImpl.loadBlocks(Pl3xMapImpl.java:173) ~[Pl3xMap-1.20.4-492.jar:?]
	at Pl3xMap-1.20.4-492.jar/net.pl3x.map.core.Pl3xMap.enable(Pl3xMap.java:211) ~[Pl3xMap-1.20.4-492.jar:?]
	at Pl3xMap-1.20.4-492.jar/net.pl3x.map.bukkit.Pl3xMapImpl.enable(Pl3xMapImpl.java:76) ~[Pl3xMap-1.20.4-492.jar:?]
	at Pl3xMap-1.20.4-492.jar/net.pl3x.map.bukkit.Pl3xMapBukkit.onEnable(Pl3xMapBukkit.java:70) ~[Pl3xMap-1.20.4-492.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[purpur-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[purpur-1.20.6.jar:1.20.6-2227-79d199c]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[purpur-1.20.6.jar:1.20.6-2227-79d199c]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:519) ~[purpur-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:618) ~[purpur-1.20.6.jar:1.20.6-2227-79d199c]
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:567) ~[purpur-1.20.6.jar:1.20.6-2227-79d199c]
	at org.bukkit.craftbukkit.CraftServer.reload(CraftServer.java:1111) ~[purpur-1.20.6.jar:1.20.6-2227-79d199c]
	at org.bukkit.Bukkit.reload(Bukkit.java:1023) ~[purpur-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:59) ~[purpur-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:177) ~[purpur-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:978) ~[purpur-1.20.6.jar:1.20.6-2227-79d199c]
	at org.bukkit.craftbukkit.CraftServer.dispatchServerCommand(CraftServer.java:963) ~[purpur-1.20.6.jar:1.20.6-2227-79d199c]
	at net.minecraft.server.dedicated.DedicatedServer.handleConsoleInputs(DedicatedServer.java:557) ~[purpur-1.20.6.jar:1.20.6-2227-79d199c]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:504) ~[purpur-1.20.6.jar:1.20.6-2227-79d199c]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1606) ~[purpur-1.20.6.jar:1.20.6-2227-79d199c]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1260) ~[purpur-1.20.6.jar:1.20.6-2227-79d199c]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:326) ~[purpur-1.20.6.jar:1.20.6-2227-79d199c]
	at java.base/java.lang.Thread.run(Thread.java:1570) ~[?:?]
[06:56:48] [Server thread/INFO]: [Pl3xMap] Disabling Pl3xMap v1.20.4-492
[06:56:48] [Server thread/INFO]: [Pl3xMap] [WARN] An error occurred with the internal webserver
```

Server: Purpur 1.20.4

I have also tried setting the internal webservers port to 30000 to see if it was a port blocking issue but that didn't help.

**Comment by granny** [comment]
You are running pl3xmap v1.20.4-492 on purpur 1.20.6-2227-79d199c.

**Comment by mitch0s** [comment]
Are the JARs version specific? I also tried the 1.21 version and that had the same issue.

**Comment by granny** [comment]
> Are the JARs version specific? I also tried the 1.21 version and that had the same issue.

Yes. You'll want to run the most recent build for the minecraft version you're on.
