### ISSUE TITLE
[Pl3xMap] [ERROR] Failed to scan world world at region Point[x=22, z=20]

### ISSUE THREAD

**Issue by makegodhere** [granny/Pl3xMap-test#70]
paper 1.21.3

```
[21:21:48 INFO]: [Pl3xMap] [ERROR] Failed to scan world world at region Point[x=22, z=20]
[21:21:48 WARN]: java.lang.RuntimeException: java.util.zip.ZipException: invalid distance too far back
[21:21:48 WARN]:        at Pl3xMap-1.21.3-511.jar//net.pl3x.map.core.renderer.task.RegionScanTask.loadRegion(RegionScanTask.java:111)
[21:21:48 WARN]:        at Pl3xMap-1.21.3-511.jar//net.pl3x.map.core.renderer.task.RegionScanTask.run(RegionScanTask.java:89)
[21:21:48 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
[21:21:48 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796)
[21:21:48 WARN]:        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
[21:21:48 WARN]:        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
[21:21:48 WARN]:        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
[21:21:48 WARN]:        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
[21:21:48 WARN]:        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
[21:21:48 WARN]: Caused by: java.util.zip.ZipException: invalid distance too far back
[21:21:48 WARN]:        at java.base/java.util.zip.InflaterInputStream.read(InflaterInputStream.java:181)
[21:21:48 WARN]:        at java.base/java.io.BufferedInputStream.fill(BufferedInputStream.java:291)
[21:21:48 WARN]:        at java.base/java.io.BufferedInputStream.read1(BufferedInputStream.java:347)
[21:21:48 WARN]:        at java.base/java.io.BufferedInputStream.implRead(BufferedInputStream.java:420)
[21:21:48 WARN]:        at java.base/java.io.BufferedInputStream.read(BufferedInputStream.java:399)
[21:21:48 WARN]:        at java.base/java.io.DataInputStream.read(DataInputStream.java:158)
[21:21:48 WARN]:        at java.base/java.io.DataInputStream.readFully(DataInputStream.java:208)
[21:21:48 WARN]:        at java.base/java.io.DataInputStream.readInt(DataInputStream.java:385)
[21:21:48 WARN]:        at Pl3xMap-1.21.3-511.jar//libs.net.querz.nbt.io.NBTInputStream.readInt(NBTInputStream.java:82)
[21:21:48 WARN]:        at Pl3xMap-1.21.3-511.jar//libs.net.querz.nbt.io.NBTInputStream.lambda$static$3(NBTInputStream.java:34)
[21:21:48 WARN]:        at Pl3xMap-1.21.3-511.jar//libs.net.querz.nbt.io.NBTInputStream.readTag(NBTInputStream.java:70)
[21:21:48 WARN]:        at Pl3xMap-1.21.3-511.jar//libs.net.querz.nbt.io.NBTInputStream.readCompound(NBTInputStream.java:144)
[21:21:48 WARN]:        at Pl3xMap-1.21.3-511.jar//libs.net.querz.nbt.io.NBTInputStream.readTag(NBTInputStream.java:70)
[21:21:48 WARN]:        at Pl3xMap-1.21.3-511.jar//libs.net.querz.nbt.io.NBTInputStream.readListTag(NBTInputStream.java:135)
[21:21:48 WARN]:        at Pl3xMap-1.21.3-511.jar//libs.net.querz.nbt.io.NBTInputStream.readTag(NBTInputStream.java:70)
[21:21:48 WARN]:        at Pl3xMap-1.21.3-511.jar//libs.net.querz.nbt.io.NBTInputStream.readCompound(NBTInputStream.java:144)
[21:21:48 WARN]:        at Pl3xMap-1.21.3-511.jar//libs.net.querz.nbt.io.NBTInputStream.readTag(NBTInputStream.java:70)
[21:21:48 WARN]:        at Pl3xMap-1.21.3-511.jar//libs.net.querz.nbt.io.NBTInputStream.readTag(NBTInputStream.java:57)
[21:21:48 WARN]:        at Pl3xMap-1.21.3-511.jar//net.pl3x.map.core.world.Region.loadChunk(Region.java:143)
[21:21:48 WARN]:        at Pl3xMap-1.21.3-511.jar//net.pl3x.map.core.world.Region.loadChunks(Region.java:111)
[21:21:48 WARN]:        at Pl3xMap-1.21.3-511.jar//net.pl3x.map.core.renderer.task.RegionScanTask.loadRegion(RegionScanTask.java:109)
[21:21:48 WARN]:        ... 8 more
```

**Comment by granny** [comment]
Without looking into it, it seems like that region file is corrupted. If there's nothing important in that region, please delete that region file and regenerate it again. Let me know if it continues to happen with a regenerated region file.

**Comment by granny** [comment]
Please join the discord server for future support requests. https://granny.dev/discord
