### ISSUE TITLE
Error occurred while enabling Pl3xMap v1.21.4-512 - java.lang.NoClassDefFoundError: org/bukkit/craftbukkit/v1_21_R3/CraftWorld

### ISSUE THREAD

**Issue by rursache** [granny/Pl3xMap-test#72]
hello,

im looking to replace dynmap as its not being updated and is broken for a long time.
however pl3xmap crashes right when loading the worlds, why?

server details:
```
[22:48:39 INFO]: [bootstrap] Running Java 21 (OpenJDK 64-Bit Server VM 21.0.4+7-Ubuntu-1ubuntu222.04; Ubuntu null) on Linux 6.12.3-061203-generic (amd64)
[22:48:39 INFO]: [bootstrap] Loading Paper 1.21.3-81-master@da71382 (2024-12-03T14:58:13Z) for Minecraft 1.21.3
```

relevant parts from `server.properties`:
```
level-name=map
level-seed=
level-type=default
server-port=25565
gamemode=survival
allow-nether=true
```

full crash log:
```
[22:48:52 INFO]: [Pl3xMap] Enabling Pl3xMap v1.21.4-512
[22:48:53 INFO]:  [ P l 3 x M a p ]   [ DEBUG ] Extracting /locale/ directory from jar... 
[22:48:53 INFO]:  [ P l 3 x M a p ]   [ DEBUG ]    exists    locale/ 
[22:48:53 INFO]:  [ P l 3 x M a p ]   [ DEBUG ]    exists    locale/lang-pl.yml 
[22:48:53 INFO]:  [ P l 3 x M a p ]   [ DEBUG ] Extracting /web/ directory from jar... 
[22:48:53 INFO]:  [ P l 3 x M a p ]   [ DEBUG ]    exists    web/ 
[22:48:53 INFO]:  [ P l 3 x M a p ]   [ DEBUG ]    writing   web/favicon.ico 
[22:48:53 INFO]:  [ P l 3 x M a p ]   [ DEBUG ]    exists    web/images/ 
[22:48:53 INFO]:  [ P l 3 x M a p ]   [ DEBUG ]    writing   web/images/armor.png 
[22:48:53 INFO]:  [ P l 3 x M a p ]   [ DEBUG ]    writing   web/images/clear.png 
[22:48:53 INFO]:  [ P l 3 x M a p ]   [ DEBUG ]    writing   web/images/foliage.png 
[22:48:53 INFO]:  [ P l 3 x M a p ]   [ DEBUG ]    writing   web/images/grass.png 
[22:48:53 INFO]:  [ P l 3 x M a p ]   [ DEBUG ]    writing   web/images/health.png 
[22:48:53 INFO]:  [ P l 3 x M a p ]   [ DEBUG ]    exists    web/images/icon/ 
[22:48:53 INFO]:  [ P l 3 x M a p ]   [ DEBUG ]    writing   web/images/icon/flowermap.png 
[22:48:53 INFO]:  [ P l 3 x M a p ]   [ DEBUG ]    writing   web/images/icon/inhabited.png 
[22:48:53 INFO]:  [ P l 3 x M a p ]   [ DEBUG ]    writing   web/images/icon/marker-icon.png 
[22:48:53 INFO]:  [ P l 3 x M a p ]   [ DEBUG ]    writing   web/images/icon/marker-shadow.png 
[22:48:53 INFO]:  [ P l 3 x M a p ]   [ DEBUG ]    writing   web/images/icon/nether_basic.png 
[22:48:53 INFO]:  [ P l 3 x M a p ]   [ DEBUG ]    writing   web/images/icon/nether_biomes.png 
[22:48:53 INFO]:  [ P l 3 x M a p ]   [ DEBUG ]    writing   web/images/icon/nether_night.png 
[22:48:53 INFO]:  [ P l 3 x M a p ]   [ DEBUG ]    writing   web/images/icon/nether_roof.png 
[22:48:53 INFO]:  [ P l 3 x M a p ]   [ DEBUG ]    writing   web/images/icon/overworld_basic.png 
[22:48:53 INFO]:  [ P l 3 x M a p ]   [ DEBUG ]    writing   web/images/icon/overworld_biomes.png 
[22:48:53 INFO]:  [ P l 3 x M a p ]   [ DEBUG ]    writing   web/images/icon/overworld_night.png 
[22:48:53 INFO]:  [ P l 3 x M a p ]   [ DEBUG ]    writing   web/images/icon/players.png 
[22:48:53 INFO]:  [ P l 3 x M a p ]   [ DEBUG ]    writing   web/images/icon/spawn.png 
[22:48:53 INFO]:  [ P l 3 x M a p ]   [ DEBUG ]    writing   web/images/icon/the_end_basic.png 
[22:48:53 INFO]:  [ P l 3 x M a p ]   [ DEBUG ]    writing   web/images/icon/the_end_biomes.png 
[22:48:53 INFO]:  [ P l 3 x M a p ]   [ DEBUG ]    writing   web/images/icon/the_end_night.png 
[22:48:53 INFO]:  [ P l 3 x M a p ]   [ DEBUG ]    writing   web/images/icon/vanilla.png 
[22:48:53 INFO]:  [ P l 3 x M a p ]   [ DEBUG ]    writing   web/images/og.png 
[22:48:53 INFO]:  [ P l 3 x M a p ]   [ DEBUG ]    exists    web/images/skins/ 
[22:48:53 INFO]:  [ P l 3 x M a p ]   [ DEBUG ]    writing   web/images/skins/steve.png 
[22:48:53 INFO]:  [ P l 3 x M a p ]   [ DEBUG ]    exists    web/images/sky/ 
[22:48:53 INFO]:  [ P l 3 x M a p ]   [ DEBUG ]    writing   web/images/sky/nether.png 
[22:48:53 INFO]:  [ P l 3 x M a p ]   [ DEBUG ]    writing   web/images/sky/overworld.png 
[22:48:53 INFO]:  [ P l 3 x M a p ]   [ DEBUG ]    writing   web/images/sky/the_end.png 
[22:48:53 INFO]:  [ P l 3 x M a p ]   [ DEBUG ]    writing   web/index.html 
[22:48:53 INFO]:  [ P l 3 x M a p ]   [ DEBUG ]    exists    web/lang/ 
[22:48:53 INFO]:  [ P l 3 x M a p ]   [ DEBUG ]    writing   web/lang/en_pt.json 
[22:48:53 INFO]:  [ P l 3 x M a p ]   [ DEBUG ]    writing   web/lang/en_us.json 
[22:48:53 INFO]:  [ P l 3 x M a p ]   [ DEBUG ]    writing   web/lang/pl_pl.json 
[22:48:53 INFO]:  [ P l 3 x M a p ]   [ DEBUG ]    writing   web/leaflet.css 
[22:48:53 INFO]:  [ P l 3 x M a p ]   [ DEBUG ]    writing   web/leaflet.js 
[22:48:53 INFO]:  [ P l 3 x M a p ]   [ DEBUG ]    writing   web/leaflet.js.map 
[22:48:53 INFO]:  [ P l 3 x M a p ]   [ DEBUG ]    writing   web/modern-normalize.css 
[22:48:53 INFO]:  [ P l 3 x M a p ]   [ DEBUG ]    writing   web/pl3xmap.js 
[22:48:53 INFO]:  [ P l 3 x M a p ]   [ DEBUG ]    writing   web/pl3xmap.js.map 
[22:48:53 INFO]:  [ P l 3 x M a p ]   [ DEBUG ]    writing   web/styles.css 
[22:48:53 INFO]:  [ P l 3 x M a p ]   [ DEBUG ]    writing   web/styles.css.map 
[22:48:53 INFO]:  [ P l 3 x M a p ]   [ DEBUG ] Registering blocks 
[22:48:53 INFO]:  [ P l 3 x M a p ]   [ DEBUG ] Cannot register any more biomes. Registered: 1024 Unregistered: 60 
[22:48:53 INFO]:  [ P l 3 x M a p ]   [ DEBUG ] Creating services 
[22:48:53 INFO]:  [ P l 3 x M a p ]   [ DEBUG ] Registering tile image types 
[22:48:53 INFO]:  [ P l 3 x M a p ]   [ DEBUG ] Registering heightmaps 
[22:48:53 INFO]:  [ P l 3 x M a p ]   [ DEBUG ] Registering renderers 
[22:48:53 INFO]:  [ P l 3 x M a p ]   [ DEBUG ] Registering worlds 
[22:48:53 ERROR]: Error occurred while enabling Pl3xMap v1.21.4-512 (Is it up to date?)
java.lang.NoClassDefFoundError: org/bukkit/craftbukkit/v1_21_R3/CraftWorld
	at Pl3xMap-1.21.4-512.jar/net.pl3x.map.bukkit.Pl3xMapImpl.lambda$loadWorlds$0(Pl3xMapImpl.java:190) ~[Pl3xMap-1.21.4-512.jar:?]
	at Pl3xMap-1.21.4-512.jar/net.pl3x.map.core.registry.WorldRegistry.getOrDefault(WorldRegistry.java:37) ~[Pl3xMap-1.21.4-512.jar:?]
	at Pl3xMap-1.21.4-512.jar/net.pl3x.map.bukkit.Pl3xMapImpl.lambda$loadWorlds$1(Pl3xMapImpl.java:189) ~[Pl3xMap-1.21.4-512.jar:?]
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596) ~[?:?]
	at Pl3xMap-1.21.4-512.jar/net.pl3x.map.bukkit.Pl3xMapImpl.loadWorlds(Pl3xMapImpl.java:189) ~[Pl3xMap-1.21.4-512.jar:?]
	at Pl3xMap-1.21.4-512.jar/net.pl3x.map.core.Pl3xMap.enable(Pl3xMap.java:235) ~[Pl3xMap-1.21.4-512.jar:?]
	at Pl3xMap-1.21.4-512.jar/net.pl3x.map.bukkit.Pl3xMapImpl.enable(Pl3xMapImpl.java:76) ~[Pl3xMap-1.21.4-512.jar:?]
	at Pl3xMap-1.21.4-512.jar/net.pl3x.map.bukkit.Pl3xMapBukkit.onEnable(Pl3xMapBukkit.java:62) ~[Pl3xMap-1.21.4-512.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-api-1.21.3-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.21.3.jar:1.21.3-81-da71382]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.21.3.jar:1.21.3-81-da71382]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-api-1.21.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:655) ~[paper-1.21.3.jar:1.21.3-81-da71382]
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:604) ~[paper-1.21.3.jar:1.21.3-81-da71382]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:768) ~[paper-1.21.3.jar:1.21.3-81-da71382]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:530) ~[paper-1.21.3.jar:1.21.3-81-da71382]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:326) ~[paper-1.21.3.jar:1.21.3-81-da71382]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1235) ~[paper-1.21.3.jar:1.21.3-81-da71382]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:340) ~[paper-1.21.3.jar:1.21.3-81-da71382]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ClassNotFoundException: org.bukkit.craftbukkit.v1_21_R3.CraftWorld
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:197) ~[paper-api-1.21.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:164) ~[paper-api-1.21.3-R0.1-SNAPSHOT.jar:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
	... 20 more
[22:48:53 INFO]: [Pl3xMap] Disabling Pl3xMap v1.21.4-512
[22:48:53 INFO]:  [ P l 3 x M a p ]   [ DEBUG ] Stopping tasks 
[22:48:53 INFO]:  [ P l 3 x M a p ]   [ DEBUG ] Stopped progress tracker: true 
[22:48:53 INFO]:  [ P l 3 x M a p ]   [ DEBUG ] Stopping internal server 
[22:48:53 INFO]:  [ P l 3 x M a p ]   [ WARN ]   An error occurred with the internal webserver 
[22:48:53 INFO]:  [ P l 3 x M a p ]   [ DEBUG ] Unregistering players 
[22:48:53 INFO]:  [ P l 3 x M a p ]   [ DEBUG ] Unregistering worlds 
[22:48:53 INFO]:  [ P l 3 x M a p ]   [ DEBUG ] Unregistering renderers 
[22:48:53 INFO]:  [ P l 3 x M a p ]   [ DEBUG ] Unregistering icons 
[22:48:53 INFO]:  [ P l 3 x M a p ]   [ DEBUG ] Unregistering heightmaps 
[22:48:53 INFO]:  [ P l 3 x M a p ]   [ DEBUG ] Unregistering tile image types 
[22:48:53 INFO]:  [ P l 3 x M a p ]   [ DEBUG ] Unregistering blocks 
```

my `config.yaml` (just changed the port):
```yaml
settings:
  # Extra logger/console output. (can be spammy)
  debug-mode: true
  # The language file to use from the locale folder.
  language-file: lang-en.yml
  # Set the web address players use to connect to your map. This
  # is only used for the client mod to know where to connect.
  web-address: http://192.168.31.100:25566
  web-directory:
    # The directory that houses the website and world tiles.
    # This is a relative path from Pl3xMap's plugin directory,
    # unless it starts with / in which case it will be treated
    # as an absolute path.
    path: web/
    # Set to true if you don't want Pl3xMap to overwrite
    # the website files on startup. (Good for servers that
    # customize these files)
    # Note: Be sure this is false when upgrading.
    read-only: false
    # The image format for tile images.
    # Built in types: bmp, gif, jpg, jpeg, png
    tile-format: png
    # The quality for image tiles (0.0 - 1.0)
    # 0.0 is low quality, high compression, small file size
    # 1.0 is high quality, no compression, large file size
    # Note: Not all image formats honor this setting.
    tile-quality: 0.0
  map:
    zoom:
      # Forces the map's zoom level to always be a multiple of this.
      # By default, the zoom level snaps to the nearest integer; lower
      # values (e.g. 0.5 or 0.1) allow for greater granularity. A
      # value of 0 means the zoom level will not be snapped.
      snap: 0.25
      # Controls how much the map's zoom level will change after a zoom in,
      # zoom out, pressing + or - on the keyboard, or using the zoom controls.
      # Values smaller than 1 (e.g. 0.5) allow for greater granularity.
      delta: 0.25
      # How many scroll pixels (as reported by L.DomEvent.getWheelDelta) mean
      # a change of one full zoom level. Smaller values will make wheel-zooming
      # faster (and vice versa).
      wheel: 120
  internal-webserver:
    # Enable the built-in web server.
    # Disable this if you want to use a standalone web server
    # such as apache or nginx.
    enabled: true
    # The interface the built-in web server should bind to.
    # This is NOT always the same as your public facing IP.
    # If you don't understand what this is,
    # leave it set to 0.0.0.0
    bind: 0.0.0.0
    # The port the built-in web server listens to.
    # Make sure the port is allocated if using Pterodactyl.
    port: 25566
    # Allows the built-in web server to follow symlinks.
    # It is generally advised against enabling this,
    # for security reasons. But you do you, boo boo.
    follow-symlinks: false
  performance:
    live-update:
      # Whether or not the real-time marker system should run.
      enabled: true
      # The number of process-threads to use for real-time marker updates on the map.
      # Value of -1 will use 50% of the available cpu-threads. (recommended)
      threads: -1
    # The number of process-threads to use for loading and scanning chunks.
    # Value of -1 will use 50% of the available cpu-threads. (recommended)
    render-threads: -1
    gc:
      # Runs the JVM GC after a render job stops to free up memory immediately.
      when-finished: true
      # Runs the JVM GC aggressively while a render is running
      # CAUTION: this _will_ slow down your renders!
      when-running: false
world-settings:
  default:
    enabled: true
    render:
      renderers:
        vintage_story: overworld_basic
      skylight: 15
  world:
    enabled: true
    render:
      renderers:
        vintage_story: overworld_basic
    ui:
      display-name: Overworld
      order: 0
  world_nether:
    render:
      renderers:
        basic: nether_basic
      skylight: 0
    ui:
      display-name: The Nether
      order: 1
  world_the_end:
    render:
      renderers:
        basic: the_end_basic
      skylight: 0
    ui:
      display-name: The End
      order: 2
```

**Comment by granny** [comment]
> `Loading Paper 1.21.3-81-master@da71382`

> `Enabling Pl3xMap v1.21.4-512`

Please use the correct version of Pl3xMap for the required minecraft version.

If you still need help, please join the discord server for support. https://granny.dev/discord
