### ISSUE TITLE
Pl3xMap fails to load on Spigot (v1.21.4)

### ISSUE THREAD

**Issue by DefinitelyRus** [granny/Pl3xMap-test#80]
Apparently an error shown below has has been showing up whenever the server boots up. It's our first time using this plugin, coming from DynMap. Our installation process was nothing unusual, just drag-and-drop to the plugins folder.

```[05:07:26 ERROR]: Error occurred while enabling Pl3xMap v1.21.4-520 (Is it up to date?)
java.lang.NoSuchFieldError: Class net.minecraft.server.level.ServerLevel does not have member field 'net.minecraft.world.level.storage.LevelStorageSource$LevelStorageAccess levelStorageAccess'
        at Pl3xMap-1.21.4-520.jar/net.pl3x.map.bukkit.BukkitWorld.<init>(BukkitWorld.java:56) ~[Pl3xMap-1.21.4-520.jar:?]
        at Pl3xMap-1.21.4-520.jar/net.pl3x.map.bukkit.Pl3xMapImpl.lambda$loadWorlds$0(Pl3xMapImpl.java:185) ~[Pl3xMap-1.21.4-520.jar:?]
        at Pl3xMap-1.21.4-520.jar/net.pl3x.map.core.registry.WorldRegistry.getOrDefault(WorldRegistry.java:37) ~[Pl3xMap-1.21.4-520.jar:?]
        at Pl3xMap-1.21.4-520.jar/net.pl3x.map.bukkit.Pl3xMapImpl.lambda$loadWorlds$1(Pl3xMapImpl.java:184) ~[Pl3xMap-1.21.4-520.jar:?]
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1596) ~[?:?]
        at Pl3xMap-1.21.4-520.jar/net.pl3x.map.bukkit.Pl3xMapImpl.loadWorlds(Pl3xMapImpl.java:184) ~[Pl3xMap-1.21.4-520.jar:?]
        at Pl3xMap-1.21.4-520.jar/net.pl3x.map.core.Pl3xMap.enable(Pl3xMap.java:235) ~[Pl3xMap-1.21.4-520.jar:?]
        at Pl3xMap-1.21.4-520.jar/net.pl3x.map.bukkit.Pl3xMapImpl.enable(Pl3xMapImpl.java:76) ~[Pl3xMap-1.21.4-520.jar:?]
        at Pl3xMap-1.21.4-520.jar/net.pl3x.map.bukkit.Pl3xMapBukkit.onEnable(Pl3xMapBukkit.java:62) ~[Pl3xMap-1.21.4-520.jar:?]
```

We initially assumed that it was an outdated version, but this one is indeed for 1.21.4. I tested it on a fresh local Spigot server and the same error showed up. Although thankfully the workaround was as simple as using an older version. I used 1.21.4-517 and it launched without any errors, both on the local server and on the deployed server.

I should add that I have not tested the plugin yet beyond this point--I'm not usually the one handling that for our server. Though I suppose that warrants an issue of its own should any further issues arise.

**Comment by Surax23** [comment]
Affirmative. Same on Purpur 1.21.4-2376-HEAD@4bf1b98 (2024-12-20T23:48:12Z) for Minecraft 1.21.4.

**Comment by jub-jan** [comment]
can confirm on spigot 1.21.4 with buildtools

**Comment by adabugra** [comment]
can confirm on Folia 1.21.4

**Comment by yonta** [comment]
can not confirm on PaperMC v1.21.4-75, Pl3xMap is working correctly.

**Comment by granny** [comment]
The error should no longer appear for those using Purpur 1.21.4 starting with Purpur build #2377.

The error will continue to appear for those using Folia until Folia is updated to use Paper's new hard-fork tooling.

A fix will eventually be released for those using Spigot.

Those who come across this issue (if it's still open) should use Pl3xMap build 517 until I resolve it.
